{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 8,
      "metadata": {
        "id": "eZYS-eWY3P0w"
      },
      "outputs": [],
      "source": [
        "!pip -q install gspread gspread-dataframe beautifulsoup4 lxml httpx"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import auth\n",
        "auth.authenticate_user()\n",
        "\n",
        "import google.auth\n",
        "import gspread\n",
        "from gspread_dataframe import set_with_dataframe\n",
        "from google.auth.transport.requests import Request\n",
        "from google.oauth2.service_account import Credentials\n",
        "\n",
        "# In Colab, default user creds are fine:\n",
        "creds, _ = google.auth.default(scopes=[\n",
        "    \"https://www.googleapis.com/auth/spreadsheets\",\n",
        "    \"https://www.googleapis.com/auth/drive.file\",\n",
        "    \"https://www.googleapis.com/auth/drive\"\n",
        "])\n",
        "gc = gspread.authorize(creds)"
      ],
      "metadata": {
        "id": "vPWTQshG3TOJ"
      },
      "execution_count": 9,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "SELLER_FEEDBACK_URL = \"https://www.ebay.co.uk/fdbk/feedback_profile/top-bargains-uk?filter=feedback_page%3ARECEIVED_AS_SELLER&sort=RELEVANCEV2\"\n",
        "\n",
        "# How many feedback pages to scan (start with 3–5; increase if needed)\n",
        "MAX_PAGES = 10\n",
        "\n",
        "# Your Google Sheet (created if not found)\n",
        "SPREADSHEET_NAME = \"eBay Feedback — top-bargains-uk\"\n",
        "WORKSHEET_NAME   = \"feedback\"\n",
        "\n",
        "# Optional: also save a CSV in Colab for download\n",
        "SAVE_CSV = True\n",
        "CSV_PATH = \"/content/feedback_top_bargains_uk.csv\"\n"
      ],
      "metadata": {
        "id": "wZu_YsOz3X-g"
      },
      "execution_count": 10,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import re, time, hashlib\n",
        "import httpx\n",
        "from bs4 import BeautifulSoup\n",
        "import pandas as pd\n",
        "from urllib.parse import urljoin, urlparse, parse_qs\n",
        "\n",
        "HEADERS = {\n",
        "    \"User-Agent\": \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36\"\n",
        "}\n",
        "\n",
        "def fetch_html(url):\n",
        "    with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:\n",
        "        r = client.get(url)\n",
        "        r.raise_for_status()\n",
        "        return r.text\n",
        "\n",
        "def make_row_id(date_text, rating, comment, item_url):\n",
        "    key = f\"{date_text}|{rating}|{comment[:200]}|{item_url or ''}\"\n",
        "    return hashlib.sha1(key.encode(\"utf-8\")).hexdigest()\n",
        "\n",
        "def extract_item_url(container):\n",
        "    # Look for any link that points to an item page\n",
        "    a = container.select_one(\"a[href*='/itm/']\")\n",
        "    if a and a.has_attr(\"href\"):\n",
        "        return a[\"href\"]\n",
        "    # fallback: sometimes the link is nested in small tags\n",
        "    for a in container.find_all(\"a\", href=True):\n",
        "        if \"/itm/\" in a[\"href\"]:\n",
        "            return a[\"href\"]\n",
        "    return None\n",
        "\n",
        "def clean_text(x):\n",
        "    return re.sub(r\"\\s+\", \" \", x).strip() if x else \"\"\n",
        "\n",
        "def parse_rating(container):\n",
        "    # Many feedback pages have an icon or text indicating Positive/Neutral/Negative\n",
        "    # Try common patterns:\n",
        "    text = container.get_text(\" \", strip=True).lower()\n",
        "    # Look for explicit words first:\n",
        "    for word in [\"positive\", \"neutral\", \"negative\"]:\n",
        "        if word in text:\n",
        "            return word.capitalize()\n",
        "    # Try alt/title attributes on images/icons\n",
        "    img = container.find(\"img\")\n",
        "    for attr in (\"alt\", \"title\"):\n",
        "        if img and img.get(attr):\n",
        "            t = img.get(attr).lower()\n",
        "            for word in [\"positive\", \"neutral\", \"negative\"]:\n",
        "                if word in t:\n",
        "                    return word.capitalize()\n",
        "    # Fallback: unknown\n",
        "    return \"Unknown\"\n",
        "\n",
        "def parse_date(container):\n",
        "    # Try a set of selectors commonly used on eBay feedback pages\n",
        "    for sel in [\".fbDate\", \".feedback-date\", \".date\", \"span[aria-label*='Feedback left on']\"]:\n",
        "        el = container.select_one(sel)\n",
        "        if el:\n",
        "            return clean_text(el.get_text())\n",
        "    # Fallback: scan for date-like strings (very loose)\n",
        "    text = container.get_text(\" \", strip=True)\n",
        "    m = re.search(r\"(?:\\d{1,2}\\s+\\w+\\s+\\d{4}|\\d{1,2}-\\d{1,2}-\\d{2,4}|\\d{1,2}\\s+\\w+)\", text)\n",
        "    return m.group(0) if m else \"\"\n",
        "\n",
        "def parse_comment(container):\n",
        "    # Try common selectors for feedback comment\n",
        "    for sel in [\".fbComment\", \".comment\", \".feedback-text\", \"p\"]:\n",
        "        el = container.select_one(sel)\n",
        "        if el and clean_text(el.get_text()):\n",
        "            return clean_text(el.get_text())\n",
        "    # Fallback: take the largest text block\n",
        "    return clean_text(container.get_text())\n",
        "\n",
        "def parse_feedback_page(html):\n",
        "    soup = BeautifulSoup(html, \"lxml\")\n",
        "\n",
        "    # Feedback rows: try a few container patterns\n",
        "    candidates = (\n",
        "        soup.select(\"div.feedback-item\") or\n",
        "        soup.select(\"li.feedback-entry\") or\n",
        "        soup.select(\"div.fbItem\") or\n",
        "        soup.select(\".fb-FeedbackList .fbBox\") or\n",
        "        soup.select(\"div#FeedbackList div\")\n",
        "    )\n",
        "\n",
        "    rows = []\n",
        "    for c in candidates:\n",
        "        comment = parse_comment(c)\n",
        "        if not comment or len(comment) < 3:\n",
        "            continue  # skip junk\n",
        "        date_text = parse_date(c)\n",
        "        rating    = parse_rating(c)\n",
        "        item_url  = extract_item_url(c)\n",
        "        rid       = make_row_id(date_text, rating, comment, item_url)\n",
        "        rows.append({\n",
        "            \"row_id\": rid,\n",
        "            \"date\": date_text,\n",
        "            \"rating\": rating,\n",
        "            \"comment\": comment,\n",
        "            \"item_url\": item_url\n",
        "        })\n",
        "    return rows\n",
        "\n",
        "def find_next_page_url(html, current_url):\n",
        "    soup = BeautifulSoup(html, \"lxml\")\n",
        "    # Look for a link element that indicates 'Next'\n",
        "    # eBay often uses ?_pgn=2 for pagination\n",
        "    a_next = None\n",
        "    for a in soup.find_all(\"a\", href=True):\n",
        "        txt = (a.get_text() or \"\").strip().lower()\n",
        "        if \"next\" in txt:\n",
        "            a_next = a\n",
        "            break\n",
        "    if a_next:\n",
        "        return urljoin(current_url, a_next[\"href\"])\n",
        "\n",
        "    # fallback: try to auto-increment ?_pgn=\n",
        "    parsed = urlparse(current_url)\n",
        "    qs = parse_qs(parsed.query)\n",
        "    pgn = None\n",
        "    for k in qs:\n",
        "        if \"pgn\" in k.lower() or \"_pgn\" in k.lower():\n",
        "            try:\n",
        "                pgn = int(qs[k][0])\n",
        "                next_q = parsed.query.replace(str(pgn), str(pgn+1))\n",
        "                return parsed._replace(query=next_q).geturl()\n",
        "            except:\n",
        "                pass\n",
        "    return None"
      ],
      "metadata": {
        "id": "yF3GfEGX3hW9"
      },
      "execution_count": 11,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "all_rows = []\n",
        "seen = set()\n",
        "\n",
        "url = SELLER_FEEDBACK_URL\n",
        "for i in range(MAX_PAGES):\n",
        "    try:\n",
        "        html = fetch_html(url)\n",
        "    except Exception as e:\n",
        "        print(f\"Error fetching page {i+1}: {e}\")\n",
        "        break\n",
        "\n",
        "    rows = parse_feedback_page(html)\n",
        "    new = [r for r in rows if r[\"row_id\"] not in seen]\n",
        "    for r in new:\n",
        "        seen.add(r[\"row_id\"])\n",
        "    all_rows.extend(new)\n",
        "\n",
        "    print(f\"Parsed page {i+1}: {len(new)} new rows, total {len(all_rows)}\")\n",
        "\n",
        "    nxt = find_next_page_url(html, url)\n",
        "    if not nxt:\n",
        "        break\n",
        "    url = nxt\n",
        "    time.sleep(1.0)  # be polite\n",
        "\n",
        "# Build DataFrame\n",
        "df = pd.DataFrame(all_rows, columns=[\"date\",\"rating\",\"comment\",\"item_url\",\"row_id\"])\n",
        "# Keep nice order\n",
        "df = df[[\"date\",\"rating\",\"comment\",\"item_url\",\"row_id\"]]\n",
        "print(\"Total feedback rows collected:\", len(df))\n",
        "df.head(3)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 88
        },
        "id": "zzZVwtAl3jlN",
        "outputId": "e40b14fd-5bd4-430b-ebd3-5593d2757452"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Parsed page 1: 0 new rows, total 0\n",
            "Total feedback rows collected: 0\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Empty DataFrame\n",
              "Columns: [date, rating, comment, item_url, row_id]\n",
              "Index: []"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-0f29a03e-8a3d-4d59-9504-6f9058479e9b\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>date</th>\n",
              "      <th>rating</th>\n",
              "      <th>comment</th>\n",
              "      <th>item_url</th>\n",
              "      <th>row_id</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-0f29a03e-8a3d-4d59-9504-6f9058479e9b')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-0f29a03e-8a3d-4d59-9504-6f9058479e9b button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-0f29a03e-8a3d-4d59-9504-6f9058479e9b');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df",
              "repr_error": "Out of range float values are not JSON compliant: nan"
            }
          },
          "metadata": {},
          "execution_count": 12
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Get or create spreadsheet\n",
        "try:\n",
        "    sh = gc.open(SPREADSHEET_NAME)\n",
        "except gspread.SpreadsheetNotFound:\n",
        "    sh = gc.create(SPREADSHEET_NAME)\n",
        "    # Share with your Google account for easy access (optional):\n",
        "    # sh.share('<your_gmail>@gmail.com', perm_type='user', role='writer')\n",
        "\n",
        "# Get or create worksheet\n",
        "try:\n",
        "    ws = sh.worksheet(WORKSHEET_NAME)\n",
        "    ws.clear()\n",
        "except gspread.WorksheetNotFound:\n",
        "    ws = sh.add_worksheet(title=WORKSHEET_NAME, rows=str(max(len(df), 100)), cols=\"10\")\n",
        "\n",
        "# Write DataFrame\n",
        "set_with_dataframe(ws, df)\n",
        "\n",
        "sheet_url = sh.url\n",
        "print(\"✅ Written to Google Sheets:\", sheet_url)\n",
        "\n",
        "if SAVE_CSV:\n",
        "    df.to_csv(CSV_PATH, index=False)\n",
        "    print(\"Also saved CSV at:\", CSV_PATH)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "7QUEHS4c3oZm",
        "outputId": "e460e3b5-931d-417d-e6d0-6a71e866bdfb"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ Written to Google Sheets: https://docs.google.com/spreadsheets/d/1CiK_3u0dBEbMz-XkHHhNVHG7AC8WlRRnBGiriegGE6w\n",
            "Also saved CSV at: /content/feedback_top_bargains_uk.csv\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "LL3V6cvC3sMo"
      },
      "execution_count": 13,
      "outputs": []
    }
  ]
}
